#!/usr/bin/env node
/**
 * scripts/vendor-fonts.mjs
 * ---------------------------------------------------------------------------
 * Downloads the three typefaces the design uses and writes self-hosted
 * @font-face CSS to assets/fonts/fonts.css.
 *
 * Run this before launch. Two reasons, both of which matter to a law firm:
 *
 *  1. PRIVACY. Every page load currently tells Google the visitor's IP and
 *     the referring URL. That visitor may be an injured person researching a
 *     claim. Self-hosting removes that disclosure entirely.
 *  2. SPEED. Two extra DNS + TLS handshakes sit on the critical render path.
 *     Self-hosted woff2 from your own origin removes them.
 *
 * After running, replace the Google Fonts <link> block in index.html with:
 *     <link rel="stylesheet" href="/assets/fonts/fonts.css">
 * and drop fonts.googleapis.com / fonts.gstatic.com from the CSP in _headers.
 *
 * Usage: node scripts/vendor-fonts.mjs
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'assets/fonts');

// The exact axes the design uses — nothing more. Every extra weight is bytes
// on the critical path that nobody sees.
const FAMILIES = [
  'Public+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400',
  'Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;1,6..72,300',
  'IBM+Plex+Mono:wght@400;500;600',
];

// Modern browsers only — woff2 with a real UA gets us the smallest files.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

async function main() {
  const url =
    'https://fonts.googleapis.com/css2?family=' +
    FAMILIES.join('&family=') +
    '&display=swap';

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
  let css = await res.text();

  await mkdir(OUT_DIR, { recursive: true });

  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]);
  const unique = [...new Set(urls)];
  console.log(`[fonts] ${unique.length} font files to vendor`);

  let n = 0;
  for (const remote of unique) {
    const file = remote.split('/').slice(-2).join('-').replace(/[^\w.-]/g, '_');
    const bin = await fetch(remote).then((r) => r.arrayBuffer());
    await writeFile(resolve(OUT_DIR, file), Buffer.from(bin));
    css = css.split(remote).join(`/assets/fonts/${file}`);
    n++;
    process.stdout.write(`\r[fonts] ${n}/${unique.length} ${file}          `);
  }

  await writeFile(
    resolve(OUT_DIR, 'fonts.css'),
    '/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n' + css
  );

  console.log('\n[fonts] Wrote assets/fonts/fonts.css');
  console.log('[fonts] Now: swap the <link> in index.html and tighten the CSP in _headers.');
}

main().catch((e) => {
  console.error('[fonts] Failed:', e.message);
  process.exit(1);
});
